export const designTokens = {
  border: {
    thin: 1,
  },
  spacing: {
    xxxs: 2,
    xxs: 4,
    xs: 6,
    sm: 8,
    md: 10,
    lg: 12,
    xl: 14,
    xxl: 16,
    xxxl: 18,
    jumbo: 20,
    huge: 24,
    giant: 32,
  },
  radii: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    xxl: 14,
    panel: 16,
    card: 18,
    hero: 20,
    pill: 999,
  },
  sizes: {
    iconTiny: 14,
    iconSmall: 18,
    iconMedium: 20,
    iconLarge: 28,
    controlMinHeight: 40,
    inputMinHeight: 44,
    iconButton: 34,
    tabBarBaseHeight: 56,
    chartMinHeight: 136,
    chartTrackMinHeight: 110,
    modalSetListMaxHeight: 340,
    bodyweightButtonWidth: 90,
    chipMinWidth: 92,
    setBoxMinWidth: 96,
    setBoxMinHeight: 106,
    setBoxMinLabelHeight: 14,
  },
  layout: {
    screenHorizontalInset: 16,
    screenTopInset: 12,
    screenBottomInset: 96,
  },
  typography: {
    displaySize: 34,
    displayLineHeight: 38,
    displayLetterSpacing: 0.4,
    titleSize: 26,
    titleLineHeight: 30,
    headingSize: 18,
    headingLineHeight: 22,
    headingLetterSpacing: 0.2,
    bodySize: 14,
    bodyLineHeight: 19,
    inputBodySize: 13,
    inputBodyLineHeight: 17,
    labelSize: 12,
    labelLineHeight: 16,
    labelLetterSpacing: 0.8,
    microSize: 10,
    microLineHeight: 14,
    microLetterSpacing: 0.9,
    tabLabelLetterSpacing: 0.7,
  },
  opacity: {
    disabled: 0.45,
    pressedStrong: 0.88,
    pressedMedium: 0.86,
    pressedSoft: 0.82,
    neonWash: 0.22,
  },
  motion: {
    overloadDurationMs: 520,
  },
  grid: {
    defaultLineGap: 48,
    maxVerticalLines: 36,
    maxHorizontalLines: 64,
  },
  overlay: {
    modalBackdrop: 'rgba(0, 0, 0, 0.58)',
  },
} as const;
