export const EXERCISE_LIBRARY = [
  'Barbell Back Squat',
  'Bench Press',
  'Deadlift',
  'Overhead Press',
  'Romanian Deadlift',
  'Barbell Row',
  'Incline Dumbbell Press',
  'Pull Up',
  'Lat Pulldown',
  'Leg Press',
  'Walking Lunges',
  'Hip Thrust',
  'Seated Cable Row',
  'Lateral Raise',
  'Biceps Curl',
  'Triceps Pushdown',
  'Calf Raise',
  'Plank',
] as const;
