#!/usr/bin/env bash
# Publishes a built Nitro OTA snapshot (.artifacts/nitro-ota/<platform>) to its
# OTA branch. Used by both the OTA publish and native APK release workflows.
#
# Required env: OTA_BRANCH, OTA_PLATFORM, OTA_VERSION
set -euo pipefail

: "${OTA_BRANCH:?OTA_BRANCH is required}"
: "${OTA_PLATFORM:?OTA_PLATFORM is required}"
: "${OTA_VERSION:?OTA_VERSION is required}"

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

WORKTREE_DIR="$(mktemp -d)"
TARGET_DIR=".artifacts/nitro-ota/${OTA_PLATFORM}"

cleanup() {
  git worktree remove --force "$WORKTREE_DIR" >/dev/null 2>&1 || true
  rm -rf "$WORKTREE_DIR"
}
trap cleanup EXIT

if git ls-remote --exit-code --heads origin "$OTA_BRANCH" >/dev/null 2>&1; then
  git fetch origin "$OTA_BRANCH"
  git worktree add "$WORKTREE_DIR" "origin/$OTA_BRANCH"
  git -C "$WORKTREE_DIR" checkout -B "$OTA_BRANCH"
else
  git worktree add --detach "$WORKTREE_DIR"
  git -C "$WORKTREE_DIR" checkout --orphan "$OTA_BRANCH"
fi

find "$WORKTREE_DIR" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
cp -R "$TARGET_DIR"/. "$WORKTREE_DIR"/

cat > "$WORKTREE_DIR/README.md" <<README
# Nitro OTA Snapshot (${OTA_PLATFORM})

This branch is auto-generated by the \`Publish Nitro OTA\` / \`Android APK Release\` GitHub Actions.
Nitro OTA clients download this branch as a ZIP archive and read \`ota.version.json\`.
README

git -C "$WORKTREE_DIR" add -A

if git -C "$WORKTREE_DIR" diff --cached --quiet; then
  echo "No OTA snapshot changes detected. Skipping commit/push."
  exit 0
fi

git -C "$WORKTREE_DIR" commit \
  -m "chore(ota): publish ${OTA_PLATFORM} ${OTA_VERSION}" \
  -m "Source commit: $(git rev-parse HEAD)"

git -C "$WORKTREE_DIR" push origin "$OTA_BRANCH" --force
