#!/usr/bin/env bash
# Publishes a built Nitro OTA snapshot (.artifacts/nitro-ota/<platform>) to its
# OTA branch. Used by both the OTA publish and native APK release workflows.
#
# Also generates bsdiff patches (via `nitro-ota patch`) from the last few
# snapshots on the branch that target the same binary, so devices already on
# one of those versions download a small patch zip instead of the full bundle.
#
# Required env: OTA_BRANCH, OTA_PLATFORM, OTA_VERSION
# Optional env: OTA_PATCH_HISTORY (number of previous snapshots to patch from, default 5)
set -euo pipefail

: "${OTA_BRANCH:?OTA_BRANCH is required}"
: "${OTA_PLATFORM:?OTA_PLATFORM is required}"
: "${OTA_VERSION:?OTA_VERSION is required}"
OTA_PATCH_HISTORY="${OTA_PATCH_HISTORY:-5}"

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

WORKTREE_DIR="$(mktemp -d)"
PREVIOUS_DIR="$(mktemp -d)"
TARGET_DIR=".artifacts/nitro-ota/${OTA_PLATFORM}"

cleanup() {
  git worktree remove --force "$WORKTREE_DIR" >/dev/null 2>&1 || true
  rm -rf "$WORKTREE_DIR" "$PREVIOUS_DIR"
}
trap cleanup EXIT

if git ls-remote --exit-code --heads origin "$OTA_BRANCH" >/dev/null 2>&1; then
  git fetch --depth="$((OTA_PATCH_HISTORY + 1))" origin \
    "+refs/heads/${OTA_BRANCH}:refs/remotes/origin/${OTA_BRANCH}"
  git worktree add "$WORKTREE_DIR" "origin/$OTA_BRANCH"
  git -C "$WORKTREE_DIR" checkout -B "$OTA_BRANCH"
else
  git worktree add --detach "$WORKTREE_DIR"
  git -C "$WORKTREE_DIR" checkout --orphan "$OTA_BRANCH"
fi

# Extract previous snapshots that target the same binary as the new one.
# Snapshots for other binaries can never be installed alongside this bundle.
TARGET_APP_VERSION="$(node -p "require('./${TARGET_DIR}/ota.meta.json').appVersion")"
OLD_ARGS=()
if git -C "$WORKTREE_DIR" rev-parse --verify --quiet HEAD >/dev/null; then
  while read -r sha; do
    dir="${PREVIOUS_DIR}/${sha}"
    mkdir -p "$dir"
    git -C "$WORKTREE_DIR" archive "$sha" | tar -x -C "$dir"

    if [ ! -f "$dir/ota.meta.json" ]; then
      continue
    fi

    read -r old_app_version old_ota_version < <(node -e "
      const meta = require('$dir/ota.meta.json');
      console.log(meta.appVersion, meta.otaVersion);
    ")

    if [ "$old_app_version" != "$TARGET_APP_VERSION" ] || [ "$old_ota_version" = "$OTA_VERSION" ]; then
      continue
    fi

    # Two commits can hold the same version (e.g. a republish); patch from the newest only.
    if [ -n "${SEEN_VERSIONS:-}" ] && grep -qx "$old_ota_version" <<<"$SEEN_VERSIONS"; then
      continue
    fi
    SEEN_VERSIONS="${SEEN_VERSIONS:-}${old_ota_version}"$'\n'

    OLD_ARGS+=(--old "$dir")
  done < <(git -C "$WORKTREE_DIR" rev-list --max-count="$OTA_PATCH_HISTORY" HEAD)
fi

if [ "${#OLD_ARGS[@]}" -gt 0 ]; then
  echo "Generating Nitro OTA patches from ${#OLD_ARGS[@]} previous snapshot(s)..."
  # Writes <TARGET_DIR>/patches/<from>-<to>.zip and adds "patches" to ota.version.json.
  node node_modules/react-native-nitro-ota/lib/module/cli.js patch "${OLD_ARGS[@]}" --new "$TARGET_DIR"
else
  echo "No previous snapshots for ${TARGET_APP_VERSION}; publishing full bundle only."
fi

find "$WORKTREE_DIR" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
cp -R "$TARGET_DIR"/. "$WORKTREE_DIR"/

# Keep patch zips out of the branch's archive zip (the full download) while
# raw.githubusercontent.com still serves them.
echo 'patches/ export-ignore' > "$WORKTREE_DIR/.gitattributes"

cat > "$WORKTREE_DIR/README.md" <<README
# Nitro OTA Snapshot (${OTA_PLATFORM})

This branch is auto-generated by the \`Publish Nitro OTA\` / \`Android APK Release\` GitHub Actions.
Nitro OTA clients download this branch as a ZIP archive and read \`ota.version.json\`.
Devices on a recent previous version download a bsdiff patch from \`patches/\` instead.
README

git -C "$WORKTREE_DIR" add -A

if git -C "$WORKTREE_DIR" diff --cached --quiet; then
  echo "No OTA snapshot changes detected. Skipping commit/push."
  exit 0
fi

git -C "$WORKTREE_DIR" commit \
  -m "chore(ota): publish ${OTA_PLATFORM} ${OTA_VERSION}" \
  -m "Source commit: $(git rev-parse HEAD)"

git -C "$WORKTREE_DIR" push origin "$OTA_BRANCH" --force
